theme: "minima"

title: "Disassemble"
author: "Ben Cherian"

timezone: Etc/UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

description: > 
Putting them back together, taking things apart 

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "example@mail.com"
#twitter_username: "twitteruser"
github_username: "cherianb59"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

rss: rss

show_excerpts: false

titles_from_headings:
  strip_title: true

collections:
  personal: # collection for personal blog posts
    output: true

header_pages:
  - resume.html
  - archive.html
#  - books.md # Commenting out for now as putting more focus on pluralsight than reading
  - bookmarks.md

plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics:
  - ${JEKYLL_CONFIG_GOOGLE_ANALYICS}


# The github repo that is to be used for looking up comments
comments_repo: cherianb59/cherianb59.github.io

defaults:
  - scope:
      path: ""
  - scope:
      path: ""
      type: posts
    values:
      tags:
        - Other # Add a default tag to all posts

# Disable highlighting to use highlightJS instead
# highlighter: none # Not supported by GitHub Pages
kramdown:
  syntax_highlighter_opts:
    disable: true